---
- name : allocate swap file
  shell:
    cmd: "fallocate -l {{swap_size}} /home/ec2-user/{{swap_size}}.swap"

- name : display file information
  shell:
    cmd: "stat /home/ec2-user/{{swap_size}}.swap"
