---
# - name: Clean Swap Space
#   hosts: all
#   become: yes
#   vars:
#      swap_size: 1G
#   tasks:
#      - name: Disable swap
#        command: "swapoff /home/ec2-user/{{swap_size}}.swap"
#        ignore_errors: yes  

#      - name: Remove swap file
#        file:
#          path: "/home/ec2-user/{{swap_size}}.swap"
#          state: absent

- hosts: all
  become: yes
  vars: 
    swap_size: 0.3G
  roles:
    - allocate_swaps
    