---
- name: install and start nginx
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      dnf:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
 